apiVersion: v1
kind: Service
metadata:
  name: aegis-databus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegis-databus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "aegis-databus.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
