apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "orchestrator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
