port: 4222
http_port: 8222
server_name: nats-3

authorization {
  users [
    { nkey: "UCMP2TWPRUVTFJ22SWCWOSK7NSMWDYTCOIHHXLSNJ6JHXXAKXX47NJUQ" }
  ]
}

jetstream {
  store_dir: /data
}

cluster {
  name: aegis-cluster
  port: 6222
  routes [
    nats://nats-1:6222
    nats://nats-2:6222
  ]
}
