apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vault-engine.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
