services:
  vault:
    build:
      context: "./engine"
    ports:
      - "8000:8000"
    restart: no

  ui:
    build:
      context: "./internal-ui"
    ports:
      - "80:80"
    depends_on:
      - vault
    restart: no

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/spec/openapi.yaml
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml:ro
    restart: no
