// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_logs.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskExecution = `-- name: CreateTaskExecution :exec
INSERT INTO agent_logs_schema.task_executions (
    id, task_id, agent_id, action_type, payload, status, error_context, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
`

type CreateTaskExecutionParams struct {
	ID           pgtype.UUID `json:"id"`
	TaskID       pgtype.UUID `json:"task_id"`
	AgentID      string      `json:"agent_id"`
	ActionType   string      `json:"action_type"`
	Payload      []byte      `json:"payload"`
	Status       string      `json:"status"`
	ErrorContext pgtype.Text `json:"error_context"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) error {
	_, err := q.db.Exec(ctx, createTaskExecution,
		arg.ID,
		arg.TaskID,
		arg.AgentID,
		arg.ActionType,
		arg.Payload,
		arg.Status,
		arg.ErrorContext,
	)
	return err
}
