// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_schema.messages (
    id, conversation_id, user_id, role, content, token_count, idempotency_key, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, conversation_id, user_id, role, content, token_count, idempotency_key, created_at
`

type CreateChatMessageParams struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	TokenCount     pgtype.Int4        `json:"token_count"`
	IdempotencyKey pgtype.UUID        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatSchemaMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.TokenCount,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i ChatSchemaMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.TokenCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessageByIdempotencyKey = `-- name: GetChatMessageByIdempotencyKey :one
SELECT id, conversation_id, user_id, role, content, token_count, idempotency_key, created_at FROM chat_schema.messages
WHERE conversation_id = $1 AND idempotency_key = $2
`

type GetChatMessageByIdempotencyKeyParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	IdempotencyKey pgtype.UUID `json:"idempotency_key"`
}

func (q *Queries) GetChatMessageByIdempotencyKey(ctx context.Context, arg GetChatMessageByIdempotencyKeyParams) (ChatSchemaMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByIdempotencyKey, arg.ConversationID, arg.IdempotencyKey)
	var i ChatSchemaMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.TokenCount,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessagesByConversation = `-- name: ListChatMessagesByConversation :many
SELECT id, conversation_id, user_id, role, content, token_count, idempotency_key, created_at FROM chat_schema.messages
WHERE conversation_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListChatMessagesByConversationParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListChatMessagesByConversation(ctx context.Context, arg ListChatMessagesByConversationParams) ([]ChatSchemaMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessagesByConversation, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSchemaMessage
	for rows.Next() {
		var i ChatSchemaMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.TokenCount,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
