// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AgentLogsSchemaTaskExecution struct {
	ID           pgtype.UUID        `json:"id"`
	TaskID       pgtype.UUID        `json:"task_id"`
	AgentID      string             `json:"agent_id"`
	ActionType   string             `json:"action_type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	ErrorContext pgtype.Text        `json:"error_context"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ChatSchemaMessage struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	TokenCount     pgtype.Int4        `json:"token_count"`
	IdempotencyKey pgtype.UUID        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IdentitySchemaUser struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PersonalInfoSchemaPersonalInfoChunk struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RawText      string             `json:"raw_text"`
	Embedding    pgvector.Vector    `json:"embedding"`
	ModelVersion string             `json:"model_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PersonalInfoSchemaSourceReference struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	TargetType string      `json:"target_type"`
	SourceID   pgtype.UUID `json:"source_id"`
	SourceType string      `json:"source_type"`
}

type PersonalInfoSchemaUserFact struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Category   pgtype.Text        `json:"category"`
	FactKey    string             `json:"fact_key"`
	FactValue  []byte             `json:"fact_value"`
	Confidence pgtype.Float8      `json:"confidence"`
	Version    pgtype.Int4        `json:"version"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ServiceLogSchemaSystemEvent struct {
	ID          pgtype.UUID        `json:"id"`
	TraceID     pgtype.UUID        `json:"trace_id"`
	ServiceName pgtype.Text        `json:"service_name"`
	Severity    pgtype.Text        `json:"severity"`
	Message     string             `json:"message"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
