// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_info.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createSourceReference = `-- name: CreateSourceReference :one
INSERT INTO personal_info_schema.source_references (
    id, user_id, target_id, target_type, source_id, source_type
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, target_id, target_type, source_id, source_type
`

type CreateSourceReferenceParams struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	TargetType string      `json:"target_type"`
	SourceID   pgtype.UUID `json:"source_id"`
	SourceType string      `json:"source_type"`
}

func (q *Queries) CreateSourceReference(ctx context.Context, arg CreateSourceReferenceParams) (PersonalInfoSchemaSourceReference, error) {
	row := q.db.QueryRow(ctx, createSourceReference,
		arg.ID,
		arg.UserID,
		arg.TargetID,
		arg.TargetType,
		arg.SourceID,
		arg.SourceType,
	)
	var i PersonalInfoSchemaSourceReference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetID,
		&i.TargetType,
		&i.SourceID,
		&i.SourceType,
	)
	return i, err
}

const deleteFact = `-- name: DeleteFact :execrows
DELETE FROM personal_info_schema.user_facts
WHERE user_id = $1 AND id = $2
`

type DeleteFactParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteFact(ctx context.Context, arg DeleteFactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFact, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllChunks = `-- name: GetAllChunks :many
SELECT id, user_id, raw_text, model_version, created_at
FROM personal_info_schema.personal_info_chunks
WHERE user_id = $1
`

type GetAllChunksRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RawText      string             `json:"raw_text"`
	ModelVersion string             `json:"model_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAllChunks(ctx context.Context, userID pgtype.UUID) ([]GetAllChunksRow, error) {
	rows, err := q.db.Query(ctx, getAllChunks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChunksRow
	for rows.Next() {
		var i GetAllChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.ModelVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFacts = `-- name: GetAllFacts :many
SELECT id, user_id, category, fact_key, fact_value, confidence, version, updated_at
FROM personal_info_schema.user_facts
WHERE user_id = $1
`

func (q *Queries) GetAllFacts(ctx context.Context, userID pgtype.UUID) ([]PersonalInfoSchemaUserFact, error) {
	rows, err := q.db.Query(ctx, getAllFacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalInfoSchemaUserFact
	for rows.Next() {
		var i PersonalInfoSchemaUserFact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.FactKey,
			&i.FactValue,
			&i.Confidence,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFactByID = `-- name: GetFactByID :one
SELECT id, user_id, category, fact_key, fact_value, confidence, version, updated_at
FROM personal_info_schema.user_facts
WHERE user_id = $1 AND id = $2
`

type GetFactByIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetFactByID(ctx context.Context, arg GetFactByIDParams) (PersonalInfoSchemaUserFact, error) {
	row := q.db.QueryRow(ctx, getFactByID, arg.UserID, arg.ID)
	var i PersonalInfoSchemaUserFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.FactKey,
		&i.FactValue,
		&i.Confidence,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceReferencesByTarget = `-- name: GetSourceReferencesByTarget :many
SELECT id, user_id, target_id, target_type, source_id, source_type
FROM personal_info_schema.source_references
WHERE user_id = $1 AND target_id = $2
`

type GetSourceReferencesByTargetParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

func (q *Queries) GetSourceReferencesByTarget(ctx context.Context, arg GetSourceReferencesByTargetParams) ([]PersonalInfoSchemaSourceReference, error) {
	rows, err := q.db.Query(ctx, getSourceReferencesByTarget, arg.UserID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalInfoSchemaSourceReference
	for rows.Next() {
		var i PersonalInfoSchemaSourceReference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetID,
			&i.TargetType,
			&i.SourceID,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO personal_info_schema.personal_info_chunks (
    id, user_id, raw_text, embedding, model_version
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, raw_text, embedding, model_version, created_at
`

type InsertChunkParams struct {
	ID           pgtype.UUID     `json:"id"`
	UserID       pgtype.UUID     `json:"user_id"`
	RawText      string          `json:"raw_text"`
	Embedding    pgvector.Vector `json:"embedding"`
	ModelVersion string          `json:"model_version"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (PersonalInfoSchemaPersonalInfoChunk, error) {
	row := q.db.QueryRow(ctx, insertChunk,
		arg.ID,
		arg.UserID,
		arg.RawText,
		arg.Embedding,
		arg.ModelVersion,
	)
	var i PersonalInfoSchemaPersonalInfoChunk
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RawText,
		&i.Embedding,
		&i.ModelVersion,
		&i.CreatedAt,
	)
	return i, err
}

const queryChunks = `-- name: QueryChunks :many
SELECT id, user_id, raw_text, embedding, model_version, created_at
FROM personal_info_schema.personal_info_chunks
WHERE user_id = $1
ORDER BY embedding <=> $2
LIMIT $3
`

type QueryChunksParams struct {
	UserID    pgtype.UUID     `json:"user_id"`
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
}

func (q *Queries) QueryChunks(ctx context.Context, arg QueryChunksParams) ([]PersonalInfoSchemaPersonalInfoChunk, error) {
	rows, err := q.db.Query(ctx, queryChunks, arg.UserID, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalInfoSchemaPersonalInfoChunk
	for rows.Next() {
		var i PersonalInfoSchemaPersonalInfoChunk
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RawText,
			&i.Embedding,
			&i.ModelVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFactWithVersion = `-- name: UpdateFactWithVersion :one
UPDATE personal_info_schema.user_facts
SET
    category = $3,
    fact_key = $4,
    fact_value = $5,
    confidence = $6,
    version = version + 1,
    updated_at = NOW()
WHERE user_id = $1 AND id = $2 AND version = $7
RETURNING id, user_id, category, fact_key, fact_value, confidence, version, updated_at
`

type UpdateFactWithVersionParams struct {
	UserID     pgtype.UUID   `json:"user_id"`
	ID         pgtype.UUID   `json:"id"`
	Category   pgtype.Text   `json:"category"`
	FactKey    string        `json:"fact_key"`
	FactValue  []byte        `json:"fact_value"`
	Confidence pgtype.Float8 `json:"confidence"`
	Version    pgtype.Int4   `json:"version"`
}

func (q *Queries) UpdateFactWithVersion(ctx context.Context, arg UpdateFactWithVersionParams) (PersonalInfoSchemaUserFact, error) {
	row := q.db.QueryRow(ctx, updateFactWithVersion,
		arg.UserID,
		arg.ID,
		arg.Category,
		arg.FactKey,
		arg.FactValue,
		arg.Confidence,
		arg.Version,
	)
	var i PersonalInfoSchemaUserFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.FactKey,
		&i.FactValue,
		&i.Confidence,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFact = `-- name: UpsertFact :one
INSERT INTO personal_info_schema.user_facts (
    id, user_id, category, fact_key, fact_value, confidence, version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE
SET
    category = EXCLUDED.category,
    fact_key = EXCLUDED.fact_key,
    fact_value = EXCLUDED.fact_value,
    confidence = EXCLUDED.confidence,
    version = user_facts.version + 1,
    updated_at = NOW()
WHERE user_facts.version = EXCLUDED.version
RETURNING id, user_id, category, fact_key, fact_value, confidence, version, updated_at
`

type UpsertFactParams struct {
	ID         pgtype.UUID   `json:"id"`
	UserID     pgtype.UUID   `json:"user_id"`
	Category   pgtype.Text   `json:"category"`
	FactKey    string        `json:"fact_key"`
	FactValue  []byte        `json:"fact_value"`
	Confidence pgtype.Float8 `json:"confidence"`
	Version    pgtype.Int4   `json:"version"`
}

func (q *Queries) UpsertFact(ctx context.Context, arg UpsertFactParams) (PersonalInfoSchemaUserFact, error) {
	row := q.db.QueryRow(ctx, upsertFact,
		arg.ID,
		arg.UserID,
		arg.Category,
		arg.FactKey,
		arg.FactValue,
		arg.Confidence,
		arg.Version,
	)
	var i PersonalInfoSchemaUserFact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.FactKey,
		&i.FactValue,
		&i.Confidence,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
