// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"context"
)

type Querier interface {
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatSchemaMessage, error)
	CreateSystemEvent(ctx context.Context, arg CreateSystemEventParams) (ServiceLogSchemaSystemEvent, error)
	GetChatMessageByIdempotencyKey(ctx context.Context, arg GetChatMessageByIdempotencyKeyParams) (ChatSchemaMessage, error)
	ListChatMessagesBySession(ctx context.Context, arg ListChatMessagesBySessionParams) ([]ChatSchemaMessage, error)
	ListSystemEvents(ctx context.Context, arg ListSystemEventsParams) ([]ServiceLogSchemaSystemEvent, error)
}

var _ Querier = (*Queries)(nil)
