// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skill_cache.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AgentsSchemaSkillCache struct {
	ID          pgtype.UUID      `json:"id"`
	Domain      string           `json:"domain"`
	Name        string           `json:"name"`
	Origin      string           `json:"origin"`
	Description string           `json:"description"`
	Payload     []byte           `json:"payload"`
	Embedding   pgvector.Vector  `json:"embedding"`
	SeedHash    string           `json:"seed_hash"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type AgentsSchemaSkillCacheRow struct {
	ID          pgtype.UUID      `json:"id"`
	Domain      string           `json:"domain"`
	Name        string           `json:"name"`
	Origin      string           `json:"origin"`
	Description string           `json:"description"`
	Payload     []byte           `json:"payload"`
	SeedHash    string           `json:"seed_hash"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

const upsertSkill = `-- name: UpsertSkill :one
INSERT INTO agents_schema.skill_cache (
    id, domain, name, origin, description, payload, embedding, seed_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (domain, name) DO UPDATE
SET
    origin      = EXCLUDED.origin,
    description = EXCLUDED.description,
    payload     = EXCLUDED.payload,
    embedding   = EXCLUDED.embedding,
    seed_hash   = EXCLUDED.seed_hash,
    updated_at  = NOW()
RETURNING id, domain, name, origin, description, payload, embedding, seed_hash, created_at, updated_at
`

type UpsertSkillParams struct {
	ID          pgtype.UUID     `json:"id"`
	Domain      string          `json:"domain"`
	Name        string          `json:"name"`
	Origin      string          `json:"origin"`
	Description string          `json:"description"`
	Payload     []byte          `json:"payload"`
	Embedding   pgvector.Vector `json:"embedding"`
	SeedHash    string          `json:"seed_hash"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) (AgentsSchemaSkillCache, error) {
	row := q.db.QueryRow(ctx, upsertSkill,
		arg.ID,
		arg.Domain,
		arg.Name,
		arg.Origin,
		arg.Description,
		arg.Payload,
		arg.Embedding,
		arg.SeedHash,
	)
	var i AgentsSchemaSkillCache
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Name,
		&i.Origin,
		&i.Description,
		&i.Payload,
		&i.Embedding,
		&i.SeedHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchSkills = `-- name: SearchSkills :many
SELECT id, domain, name, origin, description, payload, seed_hash, created_at, updated_at
FROM agents_schema.skill_cache
ORDER BY embedding <=> $1
LIMIT $2
`

func (q *Queries) SearchSkills(ctx context.Context, embedding pgvector.Vector, limit int32) ([]AgentsSchemaSkillCacheRow, error) {
	rows, err := q.db.Query(ctx, searchSkills, embedding, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentsSchemaSkillCacheRow
	for rows.Next() {
		var i AgentsSchemaSkillCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.Origin,
			&i.Description,
			&i.Payload,
			&i.SeedHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const searchSkillsByDomain = `-- name: SearchSkillsByDomain :many
SELECT id, domain, name, origin, description, payload, seed_hash, created_at, updated_at
FROM agents_schema.skill_cache
WHERE domain = $2
ORDER BY embedding <=> $1
LIMIT $3
`

func (q *Queries) SearchSkillsByDomain(ctx context.Context, embedding pgvector.Vector, domain string, limit int32) ([]AgentsSchemaSkillCacheRow, error) {
	rows, err := q.db.Query(ctx, searchSkillsByDomain, embedding, domain, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentsSchemaSkillCacheRow
	for rows.Next() {
		var i AgentsSchemaSkillCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.Origin,
			&i.Description,
			&i.Payload,
			&i.SeedHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getSkillBySeedHash = `-- name: GetSkillBySeedHash :many
SELECT id, domain, name, origin, description, payload, seed_hash, created_at, updated_at
FROM agents_schema.skill_cache
WHERE seed_hash = $1
`

func (q *Queries) GetSkillBySeedHash(ctx context.Context, seedHash string) ([]AgentsSchemaSkillCacheRow, error) {
	rows, err := q.db.Query(ctx, getSkillBySeedHash, seedHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentsSchemaSkillCacheRow
	for rows.Next() {
		var i AgentsSchemaSkillCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.Origin,
			&i.Description,
			&i.Payload,
			&i.SeedHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getSkillsByDomain = `-- name: GetSkillsByDomain :many
SELECT id, domain, name, origin, description, payload, seed_hash, created_at, updated_at
FROM agents_schema.skill_cache
WHERE domain = $1
ORDER BY name
`

func (q *Queries) GetSkillsByDomain(ctx context.Context, domain string) ([]AgentsSchemaSkillCacheRow, error) {
	rows, err := q.db.Query(ctx, getSkillsByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentsSchemaSkillCacheRow
	for rows.Next() {
		var i AgentsSchemaSkillCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Name,
			&i.Origin,
			&i.Description,
			&i.Payload,
			&i.SeedHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM agents_schema.skill_cache WHERE domain = $1 AND name = $2
`

func (q *Queries) DeleteSkill(ctx context.Context, domain, name string) error {
	_, err := q.db.Exec(ctx, deleteSkill, domain, name)
	return err
}

