// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_log.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemEvent = `-- name: CreateSystemEvent :one
INSERT INTO service_log_schema.system_events (
    id, trace_id, service_name, severity, message, metadata, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, trace_id, service_name, severity, message, metadata, created_at
`

type CreateSystemEventParams struct {
	ID          pgtype.UUID        `json:"id"`
	TraceID     pgtype.UUID        `json:"trace_id"`
	ServiceName pgtype.Text        `json:"service_name"`
	Severity    pgtype.Text        `json:"severity"`
	Message     string             `json:"message"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSystemEvent(ctx context.Context, arg CreateSystemEventParams) (ServiceLogSchemaSystemEvent, error) {
	row := q.db.QueryRow(ctx, createSystemEvent,
		arg.ID,
		arg.TraceID,
		arg.ServiceName,
		arg.Severity,
		arg.Message,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i ServiceLogSchemaSystemEvent
	err := row.Scan(
		&i.ID,
		&i.TraceID,
		&i.ServiceName,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listSystemEvents = `-- name: ListSystemEvents :many
SELECT id, trace_id, service_name, severity, message, metadata, created_at FROM service_log_schema.system_events
WHERE
    ($2::text IS NULL OR service_name = $2) AND
    ($3::text IS NULL OR severity = $3)
ORDER BY created_at DESC
LIMIT $1
`

type ListSystemEventsParams struct {
	Limit       int32       `json:"limit"`
	ServiceName pgtype.Text `json:"service_name"`
	Severity    pgtype.Text `json:"severity"`
}

func (q *Queries) ListSystemEvents(ctx context.Context, arg ListSystemEventsParams) ([]ServiceLogSchemaSystemEvent, error) {
	rows, err := q.db.Query(ctx, listSystemEvents, arg.Limit, arg.ServiceName, arg.Severity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceLogSchemaSystemEvent
	for rows.Next() {
		var i ServiceLogSchemaSystemEvent
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.ServiceName,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
