// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM vault_schema.secrets
WHERE user_id = $1 AND key_name = $2
`

type DeleteSecretParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	KeyName string      `json:"key_name"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.Exec(ctx, deleteSecret, arg.UserID, arg.KeyName)
	return err
}

const getSecretByKey = `-- name: GetSecretByKey :one
SELECT id, user_id, key_name, encrypted_value, nonce, created_at
FROM vault_schema.secrets
WHERE user_id = $1 AND key_name = $2
`

type GetSecretByKeyParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	KeyName string      `json:"key_name"`
}

func (q *Queries) GetSecretByKey(ctx context.Context, arg GetSecretByKeyParams) (VaultSchemaSecret, error) {
	row := q.db.QueryRow(ctx, getSecretByKey, arg.UserID, arg.KeyName)
	var i VaultSchemaSecret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyName,
		&i.EncryptedValue,
		&i.Nonce,
		&i.CreatedAt,
	)
	return i, err
}

const saveSecret = `-- name: SaveSecret :exec
INSERT INTO vault_schema.secrets (
    id, user_id, key_name, encrypted_value, nonce, created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
) ON CONFLICT (user_id, key_name) DO UPDATE
SET encrypted_value = EXCLUDED.encrypted_value,
    nonce = EXCLUDED.nonce
`

type SaveSecretParams struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	KeyName        string      `json:"key_name"`
	EncryptedValue []byte      `json:"encrypted_value"`
	Nonce          []byte      `json:"nonce"`
}

func (q *Queries) SaveSecret(ctx context.Context, arg SaveSecretParams) error {
	_, err := q.db.Exec(ctx, saveSecret,
		arg.ID,
		arg.UserID,
		arg.KeyName,
		arg.EncryptedValue,
		arg.Nonce,
	)
	return err
}
