{{- if or .Values.auth.hfToken .Values.global.embedding.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: embedding-api-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "embedding-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: {{ default .Values.auth.hfToken .Values.global.embedding.hfToken | quote }}
{{- end }}
